In [2]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt
import matplotlib
import warnings
warnings.filterwarnings('ignore')

cust_df = pd.read_csv("./train_santander.csv", encoding='latin-1')
print('dataset shape:', cust_df.shape)
cust_df.head(3)

dataset shape: (76020, 371)

,ID,var3,var15,imp_ent_var16_ult1,imp_op_var39_comer_ult1,imp_op_var39_comer_ult3,imp_op_var40_comer_ult1,imp_op_var40_comer_ult3,imp_op_var40_efect_ult1,imp_op_var40_efect_ult3,...,saldo_medio_var33_hace2,saldo_medio_var33_hace3,saldo_medio_var33_ult1,saldo_medio_var33_ult3,saldo_medio_var44_hace2,saldo_medio_var44_hace3,saldo_medio_var44_ult1,saldo_medio_var44_ult3,var38,TARGET
0,1,2,23,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,39205.17,0
1,3,2,34,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,49278.03,0
2,4,2,23,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,67333.77,0

# 데이터 탐색

In [3]:
cust_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 76020 entries, 0 to 76019
Columns: 371 entries, ID to TARGET
dtypes: float64(111), int64(260)
memory usage: 215.2 MB

In [4]:
cust_df['TARGET'].value_counts() #0 만족, 1 불만족
unsatisfied_cnt = cust_df[cust_df['TARGET']==1].TARGET.count()
total_cnt = cust_df.TARGET.count()

print(f'불만족 비율은 : {unsatisfied_cnt/total_cnt:.2f}')

불만족 비율은 : 0.04

In [5]:
cust_df.describe()

,ID,var3,var15,imp_ent_var16_ult1,imp_op_var39_comer_ult1,imp_op_var39_comer_ult3,imp_op_var40_comer_ult1,imp_op_var40_comer_ult3,imp_op_var40_efect_ult1,imp_op_var40_efect_ult3,...,saldo_medio_var33_hace2,saldo_medio_var33_hace3,saldo_medio_var33_ult1,saldo_medio_var33_ult3,saldo_medio_var44_hace2,saldo_medio_var44_hace3,saldo_medio_var44_ult1,saldo_medio_var44_ult3,var38,TARGET
count,76020.000000,76020.000000,76020.000000,76020.000000,76020.000000,76020.000000,76020.000000,76020.000000,76020.000000,76020.000000,...,76020.000000,76020.000000,76020.000000,76020.000000,76020.000000,76020.000000,76020.000000,76020.000000,7.602000e+04,76020.000000
mean,75964.050723,-1523.199277,33.212865,86.208265,72.363067,119.529632,3.559130,6.472698,0.412946,0.567352,...,7.935824,1.365146,12.215580,8.784074,31.505324,1.858575,76.026165,56.614351,1.172358e+05,0.039569
std,43781.947379,39033.462364,12.956486,1614.757313,339.315831,546.266294,93.155749,153.737066,30.604864,36.513513,...,455.887218,113.959637,783.207399,538.439211,2013.125393,147.786584,4040.337842,2852.579397,1.826646e+05,0.194945
min,1.000000,-999999.000000,5.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,5.163750e+03,0.000000
25%,38104.750000,2.000000,23.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6.787061e+04,0.000000
50%,76043.000000,2.000000,28.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.064092e+05,0.000000
75%,113748.750000,2.000000,40.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.187563e+05,0.000000
max,151838.000000,238.000000,105.000000,210000.000000,12888.030000,21024.810000,8237.820000,11073.570000,6600.000000,6600.000000,...,50003.880000,20385.720000,138831.630000,91778.730000,438329.220000,24650.010000,681462.900000,397884.300000,2.203474e+07,1.000000

In [6]:
cust_df.var3.value_counts()

 2         74165
 8           138
-999999      116
 9           110
 3           108
           ...
 231           1
 188           1
 168           1
 135           1
 87            1
Name: var3, Length: 208, dtype: int64

# 전처리
- 피처 선택 - id 삭제, var3 은 최빈값 2로 대체

In [7]:
cust_df.drop('ID', axis=1, inplace=True)
cust_df['var3'].replace(-999999, 2, inplace=True)

# 데이터 분할

In [8]:
X_features = cust_df.iloc[:, :-1]
y_labels = cust_df.iloc[:, -1]
X_features.shape, y_labels.shape

((76020, 369), (76020,))

# 훈련/테스트 분할

In [9]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X_features, y_labels, test_size=0.2, random_state=0)
#X_train.count()
print(f'학습 데이터 shape : {X_train.shape}, 테스트 데이터 shape : {X_test.shape}')

train_cnt = y_train.count()
test_cnt = y_test.count()
print(f'학습 데이터 값의 비율 : {y_train.value_counts()/train_cnt}')
print(f'테스트 데이터  값의 비율 : {y_test.value_counts()/test_cnt}')

학습 데이터 shape : (60816, 369), 테스트 데이터 shape : (15204, 369)
학습 데이터 값의 비율 : 0    0.960964
1    0.039036
Name: TARGET, dtype: float64
테스트 데이터  값의 비율 : 0    0.9583
1    0.0417
Name: TARGET, dtype: float64

# 검증 데이터 분할

In [10]:
X_tr, X_val, y_tr, y_val = train_test_split(X_train, y_train, test_size=0.3, random_state=0)

# XGBoost 모델 학습과 하이퍼 파라미터 튜닝

In [ ]:
%%time

from xgboost import XGBClassifier
from sklearn.metrics import roc_auc_score

xgb_clf = XGBClassifier(n_estimator=500, learning_rate=0.05, random_state=156, early_stopping_rounds=100, eval_metric='auc')
xgb_clf.fit(X_tr, y_tr, eval_set=[(X_tr, y_tr), (X_val, y_val)])
xgb_roc_score = roc_auc_score(y_test, xgb_clf.predict_proba(X_test)[:, 1])
xgb_roc_score

[16:56:44] WARNING: D:\bld\xgboost-split_1637426510059\work\src\learner.cc:576:
Parameters: { "early_stopping_rounds", "n_estimator" } might not be used.

  This could be a false alarm, with some parameters getting used by language bindings but
  then being mistakenly passed down to XGBoost core, or some parameter actually being used
  but getting flagged wrongly here. Please open an issue if you find any such cases.


[0]	validation_0-auc:0.82179	validation_1-auc:0.80068
[1]	validation_0-auc:0.83092	validation_1-auc:0.80941
[2]	validation_0-auc:0.83207	validation_1-auc:0.80903
[3]	validation_0-auc:0.83288	validation_1-auc:0.80889
[4]	validation_0-auc:0.83414	validation_1-auc:0.80924
[5]	validation_0-auc:0.83524	validation_1-auc:0.80907
[6]	validation_0-auc:0.83568	validation_1-auc:0.81005
[7]	validation_0-auc:0.83741	validation_1-auc:0.81088
[8]	validation_0-auc:0.83896	validation_1-auc:0.81305
[9]	validation_0-auc:0.83949	validation_1-auc:0.81363
[10]	validation_0-auc:0.83908	validation_1-auc:0.81277
[11]	validation_0-auc:0.83913	validation_1-auc:0.81260
[12]	validation_0-auc:0.84009	validation_1-auc:0.81325
[13]	validation_0-auc:0.84081	validation_1-auc:0.81329
[14]	validation_0-auc:0.84196	validation_1-auc:0.81380
[15]	validation_0-auc:0.84394	validation_1-auc:0.81540
[16]	validation_0-auc:0.84414	validation_1-auc:0.81573
[17]	validation_0-auc:0.84437	validation_1-auc:0.81577
[18]	validation_0-auc:0.84468	validation_1-auc:0.81569
[19]	validation_0-auc:0.84586	validation_1-auc:0.81625
[20]	validation_0-auc:0.84641	validation_1-auc:0.81619
[21]	validation_0-auc:0.84685	validation_1-auc:0.81611
[22]	validation_0-auc:0.84735	validation_1-auc:0.81671
[23]	validation_0-auc:0.84793	validation_1-auc:0.81682
[24]	validation_0-auc:0.84825	validation_1-auc:0.81675
[25]	validation_0-auc:0.84893	validation_1-auc:0.81647
[26]	validation_0-auc:0.85104	validation_1-auc:0.81724
[27]	validation_0-auc:0.85206	validation_1-auc:0.81764
[28]	validation_0-auc:0.85327	validation_1-auc:0.81873
[29]	validation_0-auc:0.85425	validation_1-auc:0.82038
[30]	validation_0-auc:0.85624	validation_1-auc:0.82231
[31]	validation_0-auc:0.85716	validation_1-auc:0.82223
[32]	validation_0-auc:0.85785	validation_1-auc:0.82261
[33]	validation_0-auc:0.85878	validation_1-auc:0.82289
[34]	validation_0-auc:0.85931	validation_1-auc:0.82389
[35]	validation_0-auc:0.86006	validation_1-auc:0.82446
[36]	validation_0-auc:0.86079	validation_1-auc:0.82537
[37]	validation_0-auc:0.86101	validation_1-auc:0.82546
[38]	validation_0-auc:0.86156	validation_1-auc:0.82593
[39]	validation_0-auc:0.86224	validation_1-auc:0.82610
[40]	validation_0-auc:0.86284	validation_1-auc:0.82603
[41]	validation_0-auc:0.86314	validation_1-auc:0.82624
[42]	validation_0-auc:0.86388	validation_1-auc:0.82694
[43]	validation_0-auc:0.86493	validation_1-auc:0.82741
[44]	validation_0-auc:0.86557	validation_1-auc:0.82757
[45]	validation_0-auc:0.86643	validation_1-auc:0.82795
[46]	validation_0-auc:0.86733	validation_1-auc:0.82860
[47]	validation_0-auc:0.86788	validation_1-auc:0.82878
[48]	validation_0-auc:0.86815	validation_1-auc:0.82881
[49]	validation_0-auc:0.86902	validation_1-auc:0.83000
[50]	validation_0-auc:0.86956	validation_1-auc:0.83040
[51]	validation_0-auc:0.86992	validation_1-auc:0.83036
[52]	validation_0-auc:0.87037	validation_1-auc:0.83061
[53]	validation_0-auc:0.87088	validation_1-auc:0.83071
[54]	validation_0-auc:0.87157	validation_1-auc:0.83092
[55]	validation_0-auc:0.87206	validation_1-auc:0.83143
[56]	validation_0-auc:0.87277	validation_1-auc:0.83170
[57]	validation_0-auc:0.87329	validation_1-auc:0.83171

# 하이퍼오피티 HyperOpt 파라미터 최적화

In [11]:
# 1. 검색 공간
from hyperopt import fmin, tpe, Trials, STATUS_OK
from hyperopt.pyll.base import scope
from sklearn.base import BaseEstimator, ClassifierMixin
from xgboost import XGBClassifier
from sklearn.model_selection import cross_val_score
from hyperopt import hp
import warnings
warnings.filterwarnings('ignore')

# 하이퍼 파라미터 검색 공간
search_space = {'n_estimators':scope.int(hp.quniform('n_estimators', 50,300,10)),
                'max_depth': scope.int(hp.quniform('max_depth', 3, 10, 1)), 
                'learning_rate': hp.loguniform('learning_rate', np.log(0.01), np.log(0.3)),
                'subsample': hp.uniform('subsample', 0.5,1.0),
                'colsample_bytree': hp.uniform('colsample_bytree', 0.5, 1.0),
                }

In [ ]:
# Sklearn 호환 XGBoost 클래스 정의
class SklearnCompatibleXGBClassifier(XGBClassifier, BaseEstimator, ClassifierMixin):
    def __sklearn_tags__(self):
        return {"non_deterministic": True}

In [12]:
# 2. 목적 함수

def objective_func_xgb(params):
    model = SklearnCompatibleXGBClassifier(
        n_estimators=100, #params['n_estimators'],
        max_depth=params['max_depth'],
        learning_rate=params['learning_rate'],
        #subsample=params['subsample'],
        colsample_bytree=params['colsample_bytree'],
        random_state=42,
        eval_metric='logloss', 
    )

    #k-fold 추가시 여기에 추가

    # cross_val_score()
    score_mean = cross_val_score(model, X_train, y_train, cv=5, scoring='accuracy').mean()
    # accuracy는 cv=3 개수만큼 roc-auc 결과를 리스트로 가짐. 이를 평균해서 반환하되 -1을 곱함.
    return {'loss': -1*score_mean , 'status': STATUS_OK}

In [1]:
# Hyperopt Trials 초기화
trials = Trials()

# Hyperparameter Tuning 실행
best_params = fmin( 
    fn=objective_func_xgb,
    space=search_space,
    algo=tpe.suggest,
    max_evals=50,
    trials=trials
    #rstate=np.random.default_rng(seed=9)
)
print('best:', best_params)

NameError: name 'Trials' is not defined

In [ ]:
best_params

# XGBoost 모델

In [ ]:
best_model = XGBClassifier(n_estimators= int(best_params['n_estimators']),
                           max_depth= int(best_params['max_depth']),
                           learning_rate= best_params['learning_rate'],
                           subsample= best_params['subsample'],
                           colsample_bytree= best_params['colsample_bytree'],
                           random_state= 42,
                           eval_metric= 'logloss'
                           )

best_model

In [ ]:
X_tr, X_val, y_tr, y_val = train_test_split(X_train, y_train, test_size=0.3, random_state=0)

In [ ]:
eval_list = [(X_tr, y_tr),(X_val, y_val)]

best_model.fit(X_tr, y_tr, 
                  early_stopping_rounds=100, 
                  eval_set=eval_list,
                  eval_metric='auc')

In [ ]:
from sklearn.metrics import roc_auc_score

xgb_roc_score = roc_auc_score(y_test, best_model.predict_proba(X_test)[:,1])
xgb_roc_score